### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by jurajmichalak1** [SelinaFelton/LightFaceNet#2]
Hello Selina,

I would like to test your models on my CPU to see what FPS I can achieve, but they are available only on CSDN which is not possible for download from Europe. Could you possibly share via Google Drive link or via Baidu cloud (I already have Baidu account but not CSDN). Thanks in advance!

**Comment by ChenyuGAO-CS** [comment]
If you want to test mobileFaceNet's FPS, you can access this link(my team member have uploaded a model on github): https://github.com/yangxue0827/MobileFaceNet_Tensorflow
But I'm sorry I can not provide other models, because I have uploaded them on a private gitlib half a year ago, I don't have access to the site now. If you have GPU, maybe it‘s better to train by yourself.

**Comment by ChenyuGAO-CS** [comment]
I accidentally found the models, and have upload on github(in folder output).
Thanks for your issue.
